name: Animint
markdown: redcarpet
highlighter: rouge

exclude: ["pandoc", "reviews", "CONTRIBUTING.md", "README.org", "book", "extras", "library"]

defaults:
  - scope:
      path: ""
    values:
      layout: default